language: python
python:
  - "3.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls coverage nose
script:  nosetests --with-coverage
after_success:
  - coveralls --config_file .coveragerc
sudo: false