# Adapted from nilearn
anguage: python

virtualenv:
  system_site_packages: true

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7"
    - DISTRIB="neurodebian" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="3.4"
    - DISTRIB="neurodebian" PYTHON_VERSION="3.4"

install: 
    - source ci/install.sh

before_script:
    - make clean

script:
    - python ci/show-python-package-versions.py
    - (cd "$TEST_RUN_FOLDER" && nosetests -s neurosynth)

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - if [[ "$COVERAGE" == "true" ]]; then cp "$TEST_RUN_FOLDER/.coverage" .; coveralls || echo "failed"; fi