language: python
python:
  - "3.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest pytest-cov
script: py.test --pyargs neurosynth --cov-report term-missing --cov=neurosynth
after_success:
  - coveralls
sudo: false